version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'