version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Building
          command: |
            echo 'npm installing'
            npm install
            CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Testing
          command: |
            echo 'testing stuff'
            npm install
            npm test
  random:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Random
          command:
            echo 'random stuff'
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - random
      - test:
          requires:
            - random